# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

    ports:
      - 3306:3306

  db2:
    image: postgres:11.4
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
